# Global Network Routing Target for Postgres.app on your MacBook Pro

# PostgreSQL Connection String
connection_uri: "postgresql://localhost/postgres"

# Default Directory Paths
directories:
  raw: "Data/raw"
  silver: "Data/silver"
  gold: "Data/gold"
    
    